# time DOCKER_BUILDKIT=1 docker build --no-cache -t docker_edk2_multi_stage_build_example2:latest . -f Dockerfile_example_2

FROM alpine:3.16.3 AS alpine_base
RUN apk add --update git

FROM alpine:3.16.3 AS NASM
RUN apk add --update wget
RUN wget https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/linux/nasm-2.15.05-0.fc31.x86_64.rpm

FROM alpine_base AS tianocore_source_code
# RUN git clone --recurse-submodule https://github.com/tianocore/edk2.git
RUN set -ex && \
      git clone https://github.com/tianocore/edk2.git && \
      cd edk2 && \
      git submodule init && \
      git submodule update BaseTools/Source/C/BrotliCompress/brotli && \
      git submodule update MdeModulePkg/Library/BrotliCustomDecompressLib/brotli && \
      git checkout edk2-stable202211

FROM python:3.9.15-slim-bullseye AS debian_base
# Change default shell to bash to avoid cannot use command source problem
SHELL ["/bin/bash", "-c"]
ENV TZ=Asia/Taipei
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN set -ex && apt-get update && \
      apt-get install -y make gcc g++ libc-dev uuid-dev alien \
        --no-install-recommends && \
      apt-get autoremove --purge && \
      apt-get -y clean && \
      rm -rf /var/lib/apt/lists/*

COPY --from=NASM /nasm-2.15.05-0.fc31.x86_64.rpm /tmp/nasm-2.15.05-0.fc31.x86_64.rpm
RUN alien /tmp/nasm-2.15.05-0.fc31.x86_64.rpm -i

FROM debian_base AS shellpkg
COPY --from=tianocore_source_code edk2/ edk2/
WORKDIR /edk2
RUN make -C BaseTools
RUN set -ex && \
      source edksetup.sh && \
      build -a X64 -t GCC5 -p ShellPkg/ShellPkg.dsc

FROM alpine:3.16.3 AS final
COPY --from=shellpkg edk2/Build/Shell/DEBUG_GCC5/X64/Shell_7C04A583-9E3E-4f1c-AD65-E05268D0B4D1.efi /Build/Shell_7C04A583-9E3E-4f1c-AD65-E05268D0B4D1.efi
COPY --from=shellpkg edk2/Build/Shell/DEBUG_GCC5/X64/Shell_EA4BB293-2D7F-4456-A681-1F22F42CD0BC.efi  /Build/Shell_EA4BB293-2D7F-4456-A681-1F22F42CD0BC.efi 
